# Generated by Django 5.1.2 on 2024-11-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='comentario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='modalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='seccion',
            field=models.CharField(max_length=100),
        ),
    ]
