# Generated by Django 5.1.2 on 2024-12-05 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_estudiante_discapacidad_alter_estudiante_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfiles',
        ),
    ]
