# Generated by Django 5.1.2 on 2024-12-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_estudiante_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='detalle_discapacidad',
            new_name='ciudad',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='discapacidad',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='lugar_nacimiento',
        ),
    ]
