# Generated by Django 5.1.2 on 2024-12-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_detalle_discapacidad_estudiante_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='representante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='representante',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
