# Generated by Django 5.1.2 on 2024-12-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_estudiante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
