# Generated by Django 5.1.2 on 2024-12-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_representante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
