# Generated by Django 5.1.2 on 2024-12-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_nombrecurso_opcioncurso_cursos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina')], default='Matutina', max_length=10)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('año_lectivo', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estudiante')),
            ],
        ),
    ]
