# Generated by Django 5.1.2 on 2024-12-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_matriculas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculas',
            options={'verbose_name': 'Matriculas', 'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterModelTable(
            name='matriculas',
            table='matriculas',
        ),
    ]
