# Generated by Django 5.1.2 on 2025-01-06 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_estudiante_curso_remove_estudiante_jornada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignaturas',
            },
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='matriculas',
            options={'verbose_name': 'Matricula', 'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AlterModelOptions(
            name='tutoria',
            options={'verbose_name': 'Tutoria', 'verbose_name_plural': 'Tutorias'},
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='representante',
            new_name='id_representante_FK',
        ),
        migrations.RenameField(
            model_name='matriculas',
            old_name='curso',
            new_name='id_curso_FK',
        ),
        migrations.RenameField(
            model_name='matriculas',
            old_name='estudiante',
            new_name='id_estudiante_FK',
        ),
        migrations.RenameField(
            model_name='representante',
            old_name='telefono',
            new_name='telefono_auxiliar',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='titulo',
            new_name='nivel_estudios',
        ),
        migrations.RenameField(
            model_name='tutoria',
            old_name='tutor',
            new_name='id_tutor_FK',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutoria',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado_academico',
            field=models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo'), ('GR', 'Graduado'), ('SU', 'Suspendido')], default='AC', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_user_FK',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='representante',
            name='id_user_FK',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representantes_usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='representante',
            name='nivel_estudios',
            field=models.CharField(choices=[('SIN', 'Sin educación formal'), ('PRI', 'Primaria incompleta'), ('PRI_C', 'Primaria completa'), ('SEC', 'Secundaria incompleta'), ('SEC_C', 'Secundaria completa'), ('TEC', 'Técnico o tecnólogo'), ('UNI', 'Universidad incompleta'), ('UNI_C', 'Universidad completa'), ('POS', 'Posgrado (Maestría o Doctorado)'), ('OTR', 'Otro')], default='SIN', max_length=10),
        ),
        migrations.AddField(
            model_name='representante',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='años_experiencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de Experiencia'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='certificaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Certificaciones'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='especializacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialización'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='id_user_FK',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutores_usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='estado',
            field=models.CharField(blank=True, choices=[('Programada', 'Programada'), ('En curso', 'En curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada'), ('Reprogramada', 'Reprogramada'), ('Pendiente', 'Pendiente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Grupal', 'Grupal'), ('Individual', 'Individual')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='año_lectivo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CargaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20, verbose_name='Período')),
                ('horas', models.PositiveIntegerField(default=0, verbose_name='Horas Asignadas')),
                ('id_asignatura_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asignaturas')),
                ('id_tutor_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tutor')),
            ],
            options={
                'verbose_name': 'Carga Docente',
                'verbose_name_plural': 'Cargas Docente',
                'db_table': 'carga-docente',
            },
        ),
        migrations.CreateModel(
            name='InscripcionTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado_inscripcion', models.CharField(choices=[('Inscrito', 'Inscrito'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('asistencia', models.BooleanField(default=False)),
                ('id_estudiante_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estudiante')),
                ('id_tutoria_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tutoria')),
            ],
            options={
                'verbose_name': 'Inscripcion a Tutoria',
                'verbose_name_plural': 'Inscripciones a Tutorias',
                'db_table': 'inscripcion-tutoria',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asignaturas')),
                ('id_curso_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Plan de Estudios',
                'db_table': 'plan-estudios',
            },
        ),
    ]
