# Generated by Django 5.1.2 on 2025-01-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_asignaturas_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_academico',
            field=models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo'), ('GR', 'Graduado'), ('SU', 'Suspendido')], default='AC', max_length=2, verbose_name='Estado Academico'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nivel_estudios',
            field=models.CharField(choices=[('Bachillerato', 'Bachillerato'), ('Tecnico', 'Técnico Superior'), ('Licenciatura', 'Licenciatura'), ('Ingenieria', 'Ingeniería'), ('Maestria', 'Maestría'), ('Doctorado', 'Doctorado')], default='Lic', max_length=100),
        ),
    ]
