# Generated by Django 5.1.2 on 2025-01-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_estudiante_estado_academico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='opcionTitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('titulo', models.CharField()),
            ],
        ),
    ]
