# Generated by Django 5.1.2 on 2025-01-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_opciontitulos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opciontitulos',
            options={'verbose_name': 'Opcion Titulo', 'verbose_name_plural': 'Opcion Titulos'},
        ),
        migrations.AlterModelTable(
            name='opciontitulos',
            table='opcion-titulos',
        ),
    ]
