# Generated by Django 5.1.2 on 2025-01-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_tutor_nivel_estudios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturas',
            name='creditos',
        ),
    ]
