# Generated by Django 5.1.2 on 2025-01-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_opciontitulos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionnivelestudios',
            name='codigo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='opciontitulos',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
    ]
