# Generated by Django 5.1.2 on 2025-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_tutoria_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='estado',
            field=models.CharField(blank=True, choices=[('Programada', 'Programada'), ('En curso', 'En curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada'), ('Reprogramada', 'Reprogramada'), ('Pendiente', 'Pendiente')], default='Programada', max_length=20, null=True),
        ),
    ]
