# Generated by Django 5.1.2 on 2025-01-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_tutoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='descripcion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
