# Generated by Django 5.1.2 on 2025-03-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_tutoria_hora_fin_alter_tutoria_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=100)),
                ('seccion', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina')], default='Matutina', max_length=10)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(blank=True, choices=[('Grupal', 'Grupal'), ('Individual', 'Individual')], max_length=10, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20, null=True)),
                ('id_tutor_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tutor')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
            },
        ),
    ]
