# Generated by Django 5.1.2 on 2025-03-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_solicitud_usuario_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='usuario_FK',
            new_name='id_user_FK',
        ),
    ]
