# Generated by Django 5.1.2 on 2024-12-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Perfiles',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.perfiles'),
        ),
    ]
