# Generated by Django 5.1.2 on 2024-12-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_user_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=10),
        ),
    ]
