# Generated by Django 5.1.2 on 2024-12-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_user_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10),
        ),
    ]
