# Generated by Django 5.1.2 on 2024-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_alter_user_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
