steps:
# Paso 1: Construir la aplicación de frontend
- name: 'node:20'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd frontend
      npm install
      npm run build

# Paso 2: Desplegar en Cloud Storage (opcional)
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', 'frontend/build', 'gs://tutoeducabucket']
