# Generated by Django 5.1.2 on 2024-12-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_representante_estudiante_representante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Curso'},
        ),
        migrations.AlterModelOptions(
            name='representante',
            options={'verbose_name': 'Representante', 'verbose_name_plural': 'Representante'},
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='representante',
            table='representante',
        ),
    ]
