# Generated by Django 5.1.2 on 2024-12-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_representante_cedula_representante_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='A', max_length=10),
        ),
    ]
