# Generated by Django 5.1.2 on 2024-12-10 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_representante_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='tutoria',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='jornada',
            field=models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina')], default='Matutina', max_length=10),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina')], default='Matutina', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutor',
                'db_table': 'tutor',
            },
        ),
        migrations.AddField(
            model_name='tutoria',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tutor'),
        ),
    ]
