# Generated by Django 5.1.2 on 2024-12-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_representante_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
