# Generated by Django 5.1.2 on 2024-12-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_representante_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tutor'),
        ),
    ]
