# Generated by Django 5.1.2 on 2024-12-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_curso_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='titulo',
            field=models.CharField(choices=[('Lic', 'Lic'), ('Ing', 'Ing'), ('Msc', 'Msc'), ('PhD', 'PhD')], default='Lic', max_length=10),
        ),
    ]
