# Generated by Django 5.1.2 on 2025-01-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_opciontitulos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='nivel_estudios',
            field=models.CharField(choices=[('TEC', 'Técnico Superior'), ('LIC', 'Licenciatura'), ('ING', 'Ingeniería'), ('MSC', 'Maestría'), ('PHD', 'PhD')], default='Lic', max_length=100),
        ),
    ]
