# Generated by Django 5.1.2 on 2025-01-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_asignaturas_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='opcionNivelEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nivel', models.CharField()),
            ],
            options={
                'verbose_name': 'Opcion Nivel Estudio',
                'verbose_name_plural': 'Opcion Nivel Estudios',
                'db_table': 'opcion-nivel-estudios',
            },
        ),
    ]
