# Generated by Django 5.1.2 on 2025-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_estudiante_estado_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
