# Generated by Django 5.1.2 on 2025-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_tutoria_hora_tutoria_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
