# Generated by Django 5.1.2 on 2024-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
