# Generated by Django 5.1.2 on 2024-10-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_profile_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
