# Generated by Django 5.1.2 on 2024-12-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_profile_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuarios', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
    ]
