# Generated by Django 5.1.2 on 2024-12-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_user_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='A', max_length=10),
        ),
    ]
